/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ChambersRouteImport } from './routes/chambers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CounselRouteImport } from './routes/counsel'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as PracticeIndexRouteImport } from './routes/practice.index'
import { Route as PracticeAreaIdRouteImport } from './routes/practice.$areaId'
import { Route as ProfilesIdRouteImport } from './routes/profiles.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ChambersRoute = ChambersRouteImport.update({
  id: '/chambers',
  path: '/chambers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CounselRoute = CounselRouteImport.update({
  id: '/counsel',
  path: '/counsel',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InsightsRoute,
} as any)
const PracticeIndexRoute = PracticeIndexRouteImport.update({
  id: '/practice/',
  path: '/practice/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeAreaIdRoute = PracticeAreaIdRouteImport.update({
  id: '/practice/$areaId',
  path: '/practice/$areaId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesIdRoute = ProfilesIdRouteImport.update({
  id: '/profiles/$id',
  path: '/profiles/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chambers': typeof ChambersRoute
  '/contact': typeof ContactRoute
  '/counsel': typeof CounselRoute
  '/faq': typeof FaqRoute
  '/insights': typeof InsightsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/practice/$areaId': typeof PracticeAreaIdRoute
  '/profiles/$id': typeof ProfilesIdRoute
  '/practice/': typeof PracticeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chambers': typeof ChambersRoute
  '/contact': typeof ContactRoute
  '/counsel': typeof CounselRoute
  '/faq': typeof FaqRoute
  '/insights': typeof InsightsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/practice/$areaId': typeof PracticeAreaIdRoute
  '/profiles/$id': typeof ProfilesIdRoute
  '/practice': typeof PracticeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/chambers': typeof ChambersRoute
  '/contact': typeof ContactRoute
  '/counsel': typeof CounselRoute
  '/faq': typeof FaqRoute
  '/insights': typeof InsightsRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/practice/$areaId': typeof PracticeAreaIdRoute
  '/profiles/$id': typeof ProfilesIdRoute
  '/practice/': typeof PracticeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/chambers'
    | '/contact'
    | '/counsel'
    | '/faq'
    | '/insights'
    | '/privacy'
    | '/terms'
    | '/insights/$slug'
    | '/practice/$areaId'
    | '/profiles/$id'
    | '/practice/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/chambers'
    | '/contact'
    | '/counsel'
    | '/faq'
    | '/insights'
    | '/privacy'
    | '/terms'
    | '/insights/$slug'
    | '/practice/$areaId'
    | '/profiles/$id'
    | '/practice'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/chambers'
    | '/contact'
    | '/counsel'
    | '/faq'
    | '/insights'
    | '/privacy'
    | '/terms'
    | '/insights/$slug'
    | '/practice/$areaId'
    | '/profiles/$id'
    | '/practice/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChambersRoute: typeof ChambersRoute
  ContactRoute: typeof ContactRoute
  CounselRoute: typeof CounselRoute
  FaqRoute: typeof FaqRoute
  InsightsRoute: typeof InsightsRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  PracticeAreaIdRoute: typeof PracticeAreaIdRoute
  ProfilesIdRoute: typeof ProfilesIdRoute
  PracticeIndexRoute: typeof PracticeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chambers': {
      id: '/chambers'
      path: '/chambers'
      fullPath: '/chambers'
      preLoaderRoute: typeof ChambersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counsel': {
      id: '/counsel'
      path: '/counsel'
      fullPath: '/counsel'
      preLoaderRoute: typeof CounselRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/practice/': {
      id: '/practice/'
      path: '/practice'
      fullPath: '/practice/'
      preLoaderRoute: typeof PracticeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$areaId': {
      id: '/practice/$areaId'
      path: '/practice/$areaId'
      fullPath: '/practice/$areaId'
      preLoaderRoute: typeof PracticeAreaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/$id': {
      id: '/profiles/$id'
      path: '/profiles/$id'
      fullPath: '/profiles/$id'
      preLoaderRoute: typeof ProfilesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InsightsRouteChildren {
  InsightsSlugRoute: typeof InsightsSlugRoute
}

const InsightsRouteChildren: InsightsRouteChildren = {
  InsightsSlugRoute: InsightsSlugRoute,
}

const InsightsRouteWithChildren = InsightsRoute._addFileChildren(
  InsightsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChambersRoute: ChambersRoute,
  ContactRoute: ContactRoute,
  CounselRoute: CounselRoute,
  FaqRoute: FaqRoute,
  InsightsRoute: InsightsRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  PracticeAreaIdRoute: PracticeAreaIdRoute,
  ProfilesIdRoute: ProfilesIdRoute,
  PracticeIndexRoute: PracticeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
